CREATE DATABASE QLSV;
GO
USE QLSV;
GO

CREATE TABLE SinhVien (
    MaSV INT PRIMARY KEY,
    HoTen VARCHAR(100),
    NgaySinh DATE
);
GO

CREATE TABLE Lop (
    MaLop INT PRIMARY KEY,
    TenLop VARCHAR(100)
);
GO

CREATE TABLE Khoa (
    MaKhoa INT PRIMARY KEY,
    TenKhoa VARCHAR(100)
);
GO

CREATE TABLE MonHoc (
    MaMon INT PRIMARY KEY,
    TenMon VARCHAR(100),
    STC INT CHECK (STC > 0)
);
GO

CREATE TABLE BoMon (
    MaBM INT PRIMARY KEY,
    TenBM VARCHAR(100),
    MaKhoa INT,
    FOREIGN KEY (MaKhoa) REFERENCES Khoa(MaKhoa)
);
GO

CREATE TABLE LopSV (
    MaLop INT,
    MaSV INT,
    ChucVu VARCHAR(50),
    PRIMARY KEY (MaLop, MaSV),
    FOREIGN KEY (MaLop) REFERENCES Lop(MaLop),
    FOREIGN KEY (MaSV) REFERENCES SinhVien(MaSV)
);
GO

CREATE TABLE GiaoVien (
    MaGV INT PRIMARY KEY,
    HoTen VARCHAR(100),
    NgaySinh DATE,
    MaBM INT,
    FOREIGN KEY (MaBM) REFERENCES BoMon(MaBM)
);
GO

CREATE TABLE GVCN (
    MaLop INT,
    MaGV INT,
    HK VARCHAR(10),
    PRIMARY KEY (MaLop, MaGV, HK),
    FOREIGN KEY (MaLop) REFERENCES Lop(MaLop),
    FOREIGN KEY (MaGV) REFERENCES GiaoVien(MaGV)
);
GO

CREATE TABLE LopHP (
    MaLopHP INT PRIMARY KEY,
    TenLopHP VARCHAR(100),
    HK VARCHAR(10),
    MaMon INT,
    MaGV INT,
    FOREIGN KEY (MaMon) REFERENCES MonHoc(MaMon),
    FOREIGN KEY (MaGV) REFERENCES GiaoVien(MaGV)
);
GO

CREATE TABLE DKMH (
    MaLopHP INT,
    MaSV INT,
    DiemTP FLOAT CHECK (DiemTP BETWEEN 0 AND 10),
    DiemThi FLOAT CHECK (DiemThi BETWEEN 0 AND 10),
    PhanTramThi FLOAT CHECK (PhanTramThi BETWEEN 0 AND 100),
    PRIMARY KEY (MaLopHP, MaSV),
    FOREIGN KEY (MaLopHP) REFERENCES LopHP(MaLopHP),
    FOREIGN KEY (MaSV) REFERENCES SinhVien(MaSV)
);
GO
