USE [QLSV]
GO

/****** Object:  Table [dbo].[GVCN]    Script Date: 3/25/2025 3:00:06 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[GVCN](
	[MaLop] [int] NOT NULL,
	[MaGV] [int] NOT NULL,
	[HK] [varchar](10) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[MaLop] ASC,
	[MaGV] ASC,
	[HK] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[GVCN]  WITH CHECK ADD  CONSTRAINT [FK__GVCN__MaGV__71D1E811] FOREIGN KEY([MaGV])
REFERENCES [dbo].[GiaoVien] ([MaGV])
GO

ALTER TABLE [dbo].[GVCN] CHECK CONSTRAINT [FK__GVCN__MaGV__71D1E811]
GO

ALTER TABLE [dbo].[GVCN]  WITH CHECK ADD FOREIGN KEY([MaLop])
REFERENCES [dbo].[Lop] ([MaLop])
GO


